### PR TITLE
Delete clients that were never built and do not build today

### PR DESCRIPTION
**Pull request by hq6**
Remove clients that are not currently being built and do not build with the current RAMCloud API.

### CODE REVIEW

**Comment by hq6** [comment]
In the absence of objections, I will push this.

**Comment by cstlee** [comment]
@johnousterhout @ankitak @jspeiser The three of you were the last to modify the following benchmarks respectively.  Do you know if they are still necessary?

- src/TransportBench.cc
- src/HintServerCrashed.cc
- src/BackupStorageBenchmark.cc

@hq6 Once you get the ok, please feel free to merge this pull request into master.

**Comment by jspeiser** [comment]
I think BackupStorageBenchmark is safe to get rid of.

**Comment by ankitak** [comment]
My modification was simply because one of my changes to something else
broke this file. So as far as i know, it can be removed.

**Comment by johnousterhout** [comment]
I took a quick look at these files, and I think it's safe to delete all of
them. They are very old; at least a couple of appear to be left over from
when we were doing our very first measurements of crash recovery
performance. My modifications to the files were made only to keep them
compiling in the face of other changes I was making.

-John-

**Comment by hq6** [comment]
I merged this in manually and it looks like github is confused, so I closed this issue manually also.

**Pull request closed without merging**
